export const STORE_PLANETS_DATA = "STORE_PLANETS_DATA";
export const STORE_VEHICLE_DATA = "STORE_VEHICLE_DATA";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const RESET_APP = "RESET_APP";
export const SELECT_PLANET = "SELECT_PLANET";
